### ISSUE TITLE
Add some missing events for pages

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPressCom-Analytics-iOS#66]
Add these events:

```
WPAnalyticsStatEditorCreatedPage
WPAnalyticsStatPageListDraftAction
WPAnalyticsStatPageListEditAction
WPAnalyticsStatPageListOpenedCellMenu
```

Once added, we can replace them [here](https://github.com/wordpress-mobile/WordPress-iOS/pull/5182/files#diff-c22650934e60fe70ee14761402220bf4R405) and in the other occurrences in the same file.

/cc @astralbodies in case you want to add anything.

**Comment by astralbodies** [comment]
@daniloercoli Does Android differentiate between page list and post list in events?

**Comment by daniloercoli** [comment]
@astralbodies - Nope. Just as an example, if the user creates a new page by tapping the + button in the pages list, `EDITOR_CREATED_POST` is bumped with a property `created_post_source => post-list`.

**Comment by diegoreymendez** [comment]
@astralbodies - Does that mean we may not want to differentiate at all?  Feel free to close this issue if that's the case.

**Comment by astralbodies** [comment]
@diegoreymendez yeah maybe lets keep it the same for now as existing code.

**Comment by diegoreymendez** [comment]
Closing.
